---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Welcome to the research website for afb_plo_aaba_2025.

Here you will find the information regarding the analysis for C. Quire's AABA 2025 poster presentation.

Visit the ABOUT page to see data cleaning, analyses, and poster PDF.

See the abstract below:

+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Abstract** (submitted 2/1/25):                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| Associations between age at first (live) birth (AFB) and incidences of osteoporosis in postmenopausal parous humans have been regularly studied. It is well-understood that reproductive factors have effects on the skeletal system, including the depletion of calcium from maternal bone stores during gestation and lactation. Additionally, it is also known that the adolescent period of human development is essential to the accrual of total bone mineral density, which in turn is crucial to the prevention of osteoporosis and other detrimental bone-density loss disorders. |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| Our study offers a comprehensive, cross-sectional analysis of the association between AFB and incidences of pregnancy- and lactation-associated osteoporosis (PLO) in pre- and perimenopausal parous persons. The aim of this study is to understand if there is a relationship between AFB and PLO, and if so, are individuals whose first births occurred before the age of peak BMD (accepted around 27 years of age) at a higher risk for PLO than individuals whose first births occurred during or after the age of peak BMD.                                                        |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| Using lumbar spine bone mineral density (LSBMD) measurements collected via DEXA scans as a measure of degree of osteoporosis, demographic information, and age at first birth reports from publicly-available CDC NHANES data, we conducted a cross-sectional study of parous, pre- and perimenopausal individuals who had available data on the factors of interest collected contiguously from 1999-2018.                                                                                                                                                                                |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| Preliminary data analyses from 2013-2016 datasets suggest that                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
