---
title: "materials"
output: html_document
date: "`r Sys.Date()`"
---

# Data

If you have any questions or concerns regarding the following, please feel free to contact me at *cquire@umich.edu*.

The data for this project were sourced from the U.S. Center for Disease Control, [National Health and Nutrition Examination Survey](<https://wwwn.cdc.gov/nchs/nhanes/Default.aspx>). NHANES survey data files are for public-use. The [Data User Agreement](<https://www.cdc.gov/nchs/policy/data-user-agreement.html#cdc_generic_section_2-terms-and-conditions>) was strictly followed.

-   Data were sourced from the "Continuous NHANES" portion of the study from the following survey years:
    -   2007-2008: <https://wwwn.cdc.gov/nchs/nhanes/continuousnhanes/default.aspx?BeginYear=2007>
    -   2009-2010: <https://wwwn.cdc.gov/nchs/nhanes/continuousnhanes/default.aspx?BeginYear=2009> 
    -   2013-2014: <https://wwwn.cdc.gov/nchs/nhanes/continuousnhanes/default.aspx?BeginYear=2013>
    -   2017-2018: <https://wwwn.cdc.gov/nchs/nhanes/continuousnhanes/default.aspx?BeginYear=2017>

-   The following analytic guidelines were followed: <https://wwwn.cdc.gov/nchs/nhanes/analyticguidelines.aspx#analytic-guidelines>

# References

Fukushima, Maiko, Maiko Kawajiri, Mikako Yoshida, Yoko Takeishi, Yasuka Nakamura, and Toyoko Yoshizawa. “Prevalence of Pregnancy- and Lactation-Associated Osteoporosis in the Postpartum Period: A Systematic Review and Meta-Analysis.” Drug Discoveries & Therapeutics 18, no. 4 (August 31, 2024): 220–28. https://doi.org/10.5582/ddt.2024.01037.

Gak, Nataliya, Ali Abbara, Waljit S. Dhillo, Richard Keen, and Alexander N. Comninos. “Current and Future Perspectives on Pregnancy and Lactation-Associated Osteoporosis.” Frontiers in Endocrinology 15 (December 5, 2024): 1494965. https://doi.org/10.3389/fendo.2024.1494965.

Gatenby, Charlotte, and Paul Simpson. “Menopause: Physiology, Definitions, and Symptoms.” Best Practice & Research Clinical Endocrinology & Metabolism 38, no. 1 (January 2024): 101855. https://doi.org/10.1016/j.beem.2023.101855.

Jáuregui, Edwin, Marianella Galvis, Viviana Moncaleano, Katherine González, and Yezid Muñoz. “Bone Mineral Density Reference Values by DXA Scan in a Population of Healthy Adults in Bogota.” Revista Colombiana de Reumatología (English Edition) 28, no. 1 (January 2021): 46–51. https://doi.org/10.1016/j.rcreue.2020.06.010.

Kaya, Aski, Ozan Doğan, Alper Başbuğ, Cemil Sönmez, Mehmet Sungur, and Safinaz Ataoğlu. “An Evaluation of the Association of Reproductive History and Multiple Births during Adolescence with Postmenopausal Osteoporosis.” Geburtshilfe Und Frauenheilkunde 79, no. 03 (March 2019): 300–307. https://doi.org/10.1055/a-0743-7260.

Looker, A. C., H. W. Wahner, W. L. Dunn, M. S. Calvo, T. B. Harris, S. P. Heyse, C. C. Johnston Jr, and R. Lindsay. “Updated Data on Proximal Femur Bone Mineral Levels of US Adults.” Osteoporosis International 8, no. 5 (August 1, 1998): 468–90. https://doi.org/10.1007/s001980050093.
“Menopause.” Nature Reviews Disease Primers 1, no. 1 (April 23, 2015): 15054. https://doi.org/10.1038/nrdp.2015.54.

on behalf of the Scientific Advisory Board of the European Society for Clinical and Economic Aspects of Osteoporosis (ESCEO) and the Committees of Scientific Advisors and National Societies of the International Osteoporosis Foundation (IOF), J.A. Kanis, C. Cooper, R. Rizzoli, and J.-Y. Reginster. “European Guidance for the Diagnosis and Management of Osteoporosis in Postmenopausal Women.” Osteoporosis International 30, no. 1 (January 18, 2019): 3–44. https://doi.org/10.1007/s00198-018-4704-5.

Qian, Ying, Jingming Wang, Aifang Wu, and Weimin Huang. “Pregnancy- and Lactation-Associated Osteoporosis: A Case Series of 6 Patients.” Medicine 103, no. 12 (March 22, 2024): e37430. https://doi.org/10.1097/MD.0000000000037430.

Salari, Pooneh, and Mohammad Abdollahi. “The Influence of Pregnancy and Lactation on Maternal Bone Health: A Systematic Review,” July 2014.

Scioscia, Maria Florencia, and Maria Belen Zanchetta. “Recent Insights into Pregnancy and Lactation-Associated Osteoporosis (PLO).” International Journal of Women’s Health Volume 15 (August 2023): 1227–38. https://doi.org/10.2147/IJWH.S366254.

Stini, William A. “Osteoporosis in Biocultural Perspective,” n.d.
Tang, Yuchen, Bo Peng, Jinmin Liu, Zhongcheng Liu, Yayi Xia, and Bin Geng. “Systemic Immune-Inflammation Index and Bone Mineral Density in Postmenopausal Women: A Cross-Sectional Study of the National Health and Nutrition Examination Survey (NHANES) 2007-2018.” Frontiers in Immunology 13 (September 8, 2022): 975400. https://doi.org/10.3389/fimmu.2022.975400.

Xue, Shanshan, Oumer Kemal, Meihan Lu, Lisa M. Lix, William D. Leslie, and Shuman Yang. “Age at Attainment of Peak Bone Mineral Density and Its Associated Factors: The National Health and Nutrition Examination Survey 2005–2014.” Bone 131 (February 2020): 115163. https://doi.org/10.1016/j.bone.2019.115163.

Yang, Yimei, Shanshan Wang, and Hui Cong. “Association between Parity and Bone Mineral Density in Postmenopausal Women.” BMC Women’s Health 22, no. 1 (December 2022): 87. https://doi.org/10.1186/s12905-022-01662-9.

